name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-release:
    name: Build Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: syncpair
            asset_name: syncpair-linux-amd64
          - os: ubuntu-latest
            rust_target: aarch64-unknown-linux-gnu
            artifact_name: syncpair
            asset_name: syncpair-linux-arm64
          - os: macos-latest
            artifact_name: syncpair
            asset_name: syncpair-macos-amd64
          - os: macos-14
            artifact_name: syncpair
            asset_name: syncpair-macos-arm64
          - os: windows-latest
            artifact_name: syncpair.exe
            asset_name: syncpair-windows-amd64.exe

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install target for crossâ€‘compile (if needed)
        if: env.rust_target != ''
        run: |
          rustup target add ${{ env.rust_target }}
          echo "CARGO_BUILD_TARGET=${{ env.rust_target }}" >> $GITHUB_ENV
      - name: Build
        run: |
          if [ -n "${{ env.CARGO_BUILD_TARGET }}" ]; then
            cargo build --release --target ${{ env.CARGO_BUILD_TARGET }} --verbose
          else
            cargo build --release --verbose
          fi
        shell: bash

      - name: Set build path
        run: |
          if [ -n "${{ env.CARGO_BUILD_TARGET }}" ]; then
            echo "BUILD_PATH=target/${{ env.CARGO_BUILD_TARGET }}/release" >> $GITHUB_ENV
          else
            echo "BUILD_PATH=target/release" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Rename Binary
        run: mv ${{ env.BUILD_PATH }}/${{ matrix.artifact_name }} ${{ env.BUILD_PATH }}/${{ matrix.asset_name }}
        shell: bash

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.BUILD_PATH }}/${{ matrix.asset_name }}
          draft: false
          prerelease: false
